const appsData = [
    { title: 'Smart Audiocut', category: 'Audio' },
    { title: 'Sound Meter', category: 'Audio' },
    { title: 'Video To Mp3 Converter', category: 'Audio' },
    { title: 'Minimo Music Player', category: 'Audio' },
    { title: 'Man Hair Style', category: 'Beauty' },
    { title: 'Mens Makeover', category: 'Beauty' },
    { title: 'Smart Mirror', category: 'Beauty' },
    { title: 'Ultimate Speed Test', category: 'Connectivity' },
    { title: 'Wifi Analyzer', category: 'Connectivity' },
    { title: 'Internet Speed Meter', category: 'Connectivity' },
    { title: 'Portable Wifi', category: 'Connectivity' },
    { title: 'Wifi Booster', category: 'Connectivity' },
    { title: 'Ebook Reader', category: 'Entertainment' },
    { title: 'Soccer Live Scores', category: 'Entertainment' },
    { title: 'Story World', category: 'Entertainment' },
    { title: 'Apk Manager', category: 'Files' },
    { title: 'Data Recovery App', category: 'Files' },
    { title: 'Easy Backup Restore Pro', category: 'Files' },
    { title: 'Tt Downloader', category: 'Files' },
    { title: '30 Days Workout Challenge', category: 'Fitness' },
    { title: '30 Days Workout Plan', category: 'Fitness' },
    { title: '7 Minute Workout', category: 'Fitness' },
    { title: 'Express Workout', category: 'Fitness' },
    { title: 'My Personal Trainer', category: 'Fitness' },
    { title: 'Plank Workout', category: 'Fitness' },
    { title: 'Air Horn', category: 'Fun' },
    { title: 'Fake Call Generator', category: 'Fun' },
    { title: 'Make Me Old', category: 'Fun' },
    { title: 'Voice Changer', category: 'Fun' },
    { title: 'Christmas Pip Camera Effects', category: 'Fun' },
    { title: 'Fake Gps Location', category: 'Fun' },
    { title: 'Blood Pressure Calculator', category: 'Health' },
    { title: 'Easy BMI Calculator Pro', category: 'Health' },
    { title: 'Eva Period & Ovulation Tracker', category: 'Health' },
    { title: 'Health Calculator', category: 'Health' },
    { title: 'Lose Weight', category: 'Health' },
    { title: 'Pill App', category: 'Health' },
    { title: 'Drum Pad', category: 'Music' },
    { title: 'Music Bass Boss', category: 'Music' },
    { title: 'Music Player Pro', category: 'Music' },
    { title: 'My Music Vault', category: 'Music' },
    { title: 'Advance Pdf App', category: 'Productivity' },
    { title: 'Color Notes', category: 'Productivity' },
    { title: 'Cpu Expert', category: 'Productivity' },
    { title: 'Magic Phone Scan - Professional Version', category: 'Productivity' },
    { title: 'Office Master', category: 'Productivity' },
    { title: 'Pdf Toolkit', category: 'Productivity' },
    { title: 'Adult Coloring Book', category: 'Relaxing Fun' },
    { title: 'Ar Drawing Sketch With Trace', category: 'Relaxing Fun' },
    { title: 'Art Mosaic Maker', category: 'Relaxing Fun' },
    { title: 'Color By Numbers App', category: 'Relaxing Fun' },
    { title: 'Coloring App', category: 'Relaxing Fun' },
    { title: 'Colorize', category: 'Relaxing Fun' },
    { title: 'Iq Test Genius', category: 'Skills' },
    { title: 'Visual Memory IQ Test', category: 'Skills' },
    { title: 'Crossword App', category: 'Skills' },
    { title: 'Ielts Preparation', category: 'Skills' },
    { title: 'Typing Speed Tester', category: 'Skills' },
    { title: 'Aio Phone Speed Up', category: 'Utilities' },
    { title: 'Android Cleaner', category: 'Utilities' },
    { title: 'Blue Vpn: Superfast Vpn', category: 'Utilities' },
    { title: 'Digital Compass', category: 'Utilities' },
    { title: 'Fast Cleaner', category: 'Utilities' },
    { title: 'Flashlight Pro', category: 'Utilities' },
    { title: 'Ai Background Remover', category: 'Video And Images' },
    { title: 'Artistic Photo Editor And Collage Maker', category: 'Video And Images' },
    { title: 'Blur Image Background', category: 'Video And Images' },
    { title: 'Colorize Photo Editor', category: 'Video And Images' },
    { title: 'Pro Sketcher', category: 'Video And Images' },
    { title: 'Quick Screen Recorder', category: 'Video And Images' },
];

const appsByCategory = appsData.reduce((acc, app) => {
    if (!acc[app.category]) {
        acc[app.category] = [];
    }
    acc[app.category].push(app);
    return acc;
}, {});
